version: "3.8"
services:
  web : 
    build : "./frontend"
    ports:
      - "80:5173"
  api :
    build : "./backend"
    ports:
      - "8000:8000"
    network_mode: "host"
    env_file:
      - "./backend/.env"